### ISSUE TITLE
Supplemental goods not working for other players in MP

### ISSUE THREAD

**Issue by rrosbach** [jakobharder/anno-1800-jakobs-mods#54]
Hi Jakob,

we are playing a multiplayer game with 3 human players and Hugo as an AI player. I'm the host in this game and we tested it with multiple setups, but none of my other mates was able to actually successfully use the supplemental goods, despite enough production and the activation via lifestyle goods. For me it's working perfectly fine, but the others it doesn't work at all. It seems like everything is working, but only need fulfillment for the original good is only working for me as the host.

We tried a lot of stuff to be sure to have synchronized extra goods folders and mod folders overall, but nothing worked. We even tried to change/turn on the trigger on "UsedBySecondParties" in alternative-needs/assets.include.xml, even though I#m not sure what the purpose of it is.

Can you please help us? Otherwise we need to turn extra goods off due to fairness reasons.

Regards,
Roman

**Comment by jakobharder** [comment]
I have to look into it, but until then you can disable the alternative needs if remove one line in the features.include.xml in the mod folder.

**Comment by Hirschberger-Alexander** [comment]
Hello. 
I have the same problem in a multiplayer game. We are three players and one AI. In our game only the host has access to the supplemental goods. I found a hack-y solution for this, which at least helped us. Maybe it will be of some use here. To activate the needs for a non host player, the player has to switch to Cape Trelawney (mod two Crowns works too) and then back to the old world. The switch then activates the supplemental goods in the old world and cape trelawney. 

For this to work, "assets.include.xml" in "[Shared]Extra Goods (Jakob)\data\jakob\alternative-needs" must be replaced with the file in the attachment.

The File:
[assets.include.zip](https://github.com/jakobharder/anno-1800-jakobs-mods/files/10412475/assets.include.zip)


best regards

Hirschberger

**Comment by rrosbach** [comment]
Hi Alex,
we will try to get it running with your approach.
If its working again, we will fully use it again. Otherwise I won't use the extra goods anymore.

I didn't dig deep into modding yet, but I would be free to help if necessary. As a C# developer I could certainly help with a little more knowledge of how the structure of the xmls has to be.

Regards,
Roman

BTW: Sind hier eigentlich alle deutsch? :)

**Comment by jakobharder** [comment]
I moved the alternative needs feature into a separate mod with [v5.4](https://github.com/jakobharder/anno-1800-jakobs-mods/releases/tag/v5.4).

I've tried quite a few things but none of them were reliable for multiplayer.
So this way you can still use the extra goods productions (for Upgradable Workers etc.) without unfair buffs for one player.

**Comment by jakobharder** [comment]
Should be fixed with #68, v5.6
