### ISSUE TITLE
Tier 1 Pescatarians house going in the news for lacking university

### ISSUE THREAD

**Issue by Rufert** [jakobharder/anno-1800-jakobs-mods#57]
As the title says. Have an Island with only Pescatarians, got an article about them lacking university.

They had all needs met except Bread, Olive Soap and Tools.

**Comment by jakobharder** [comment]
That's unfortunately a flaw in the game I cannot change.
I increased the number of the residents to 4000 before the warning is shown though.

Will close the ticket when released.

**Comment by Rufert** [comment]
Very good figured I'd mention it, as I understand there's quite a lot in the game that's a bit weird about being modded. 
Keep up the good work!

**Comment by jakobharder** [comment]
fixed with #62
